modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/thepopulous/savageandravage" #optional
[[mods]] #mandatory
modId="savage" #mandatory
version="0.1.1.2" #mandatory
displayName="Savage and Ravage" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.populousteam.com/" #optional
#logoFile="savageandravage.png" #optional
credits="The Populous" #optional
authors="Bagu-chan, MCVinnyq, Farcr, Five, JacksonPlayz, Scarecrow, Bailey, Bloo, Hudthn, Gauge, Ian, and Voliant" #optional
description="Be careful when a raid happens - there are dangerous new foes around!"

[[dependencies.savageandravage]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.1.10,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.savageandravage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
#[[dependencies.savageandravage]]
    #modId="quark"
    #mandatory="false"
    #versionRange="[194,)"
    #ordering="NONE"
    #side="BOTH"